### ISSUE TITLE
What is the performance impact of sandbox?

### ISSUE THREAD

**Issue by garlicgambit** [cloudflare/sandbox#12]
Does sandbox affect the performance of programs?

**Comment by ignatk** [comment]
The tool itself does not have any performance impact itself - the toolkit only sets up seccomp filters for the application, but otherwise is inactive on runtime:
  * if you use `libsandbox.so` - the code from the library runs only on process startup to set up the filters
  * if you use `sandboxify` - it is the same as `libsandbox.so`, but even more - the `sandboxify` code is completely evicted from the process address space once the main application gets execution control, so the code is not even there

The only potential performance impact you might get is the impact of the Linux seccomp filters themselves. The kernel will execute these filters for each system call the application makes so the exact impact depends on how complex these filters are and how many system calls a particular application does. In other words - it is dependent on a particular workflow.

But in general, for a simple system call `allowlist`/`denylist` filters - there should be no visible impact as the resulting filters are quite simple.

**Comment by garlicgambit** [comment]
Thanks for the response.
