### ISSUE TITLE
reimplementing minijail ?

### ISSUE THREAD

**Issue by kees** [cloudflare/sandbox#6]
Check out:
https://github.com/google/minijail

It does the same things (even LD_PRELOAD), and way more.

**Comment by ignatk** [comment]
The concept of this project is not new and indeed there are similar solutions, including minijail, systemd `SystemCallFilter` directive and others.

Every approach has pros and cons. minijail in particular is much more functional, but on the other hand it is much more complex to configure. Also, from a quick glance it is rather tightly coupled to Android/Chrome OS, but less usable on generic Linux distributions. It is probably that's why we don't see a wider adoption of the package in popular Linux distributions.

This project aims to provide rather basic sandboxing functionality while being easy to use and configure for quick and painless adoption. If the project requires much more complex and featurefull sandbox configuration, this is probably not the best tool to use and I would even say it would be probably best not to use any tool at all. Rather add seccomp rules directly into the codebase.

Hope this helps
